In [1]:
'''
この動画を参考に、tfを少しいじってみる
https://www.youtube.com/watch?v=LqtCckIXQHs

tfで簡単に線形回帰をやってみる。
'''

'\nこの動画を参考に、tfを少しいじってみる\nhttps://www.youtube.com/watch?v=LqtCckIXQHs\n'

In [5]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler

In [6]:
housing = fetch_california_housing()

In [7]:
housing

{'DESCR': 'California housing dataset.\n\nThe original database is available from StatLib\n\n    http://lib.stat.cmu.edu/datasets/\n\nThe data contains 20,640 observations on 9 variables.\n\nThis dataset contains the average house value as target variable\nand the following input variables (features): average income,\nhousing average age, average rooms, average bedrooms, population,\naverage occupation, latitude, and longitude in that order.\n\nReferences\n----------\n\nPace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\nStatistics and Probability Letters, 33 (1997) 291-297.\n\n',
 'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ..., 
        [   1.7       ,   17.    

In [8]:
housing_X = housing.data
housing_y = housing.target

In [9]:
housing_X

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ..., 
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [10]:
scaler = StandardScaler()
scaled_housing_X = scaler.fit_transform(housing_X)

In [18]:
scaled_housing_X
scaled_housing_X_with_bias = np.c_[np.ones((scaled_housing_X.shape[0], 1)), scaled_housing_X]
scaled_housing_X_with_bias

array([[ 1.        ,  2.34476576,  0.98214266, ..., -0.04959654,
         1.05254828, -1.32783522],
       [ 1.        ,  2.33223796, -0.60701891, ..., -0.09251223,
         1.04318455, -1.32284391],
       [ 1.        ,  1.7826994 ,  1.85618152, ..., -0.02584253,
         1.03850269, -1.33282653],
       ..., 
       [ 1.        , -1.14259331, -0.92485123, ..., -0.0717345 ,
         1.77823747, -0.8237132 ],
       [ 1.        , -1.05458292, -0.84539315, ..., -0.09122515,
         1.77823747, -0.87362627],
       [ 1.        , -0.78012947, -1.00430931, ..., -0.04368215,
         1.75014627, -0.83369581]])

In [20]:
X = tf.placeholder(tf.float32, ([None, scaled_housing_X_with_bias.shape[1]]))
t = tf.placeholder(tf.float32, ([None,1]))
theta = tf.Variable(tf.random_uniform([scaled_housing_X.shape[1] + 1, 1], -1.0, 1.0))


y_pred = tf.matmul(X,theta)

mse = tf.reduce_mean(tf.square(y_pred - t))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(mse)

In [26]:
n_epochs  = 5000

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        sess.run(train, feed_dict={X: scaled_housing_X_with_bias,
                                                       t: housing_y.reshape(-1,1)
                                  })
    
    best_theta = theta.eval()


print(best_theta)

[[ 2.06855249]
 [ 0.83121955]
 [ 0.11909194]
 [-0.26847482]
 [ 0.30810073]
 [-0.00439998]
 [-0.03938918]
 [-0.89590257]
 [-0.86674058]]


In [22]:
'''
sklearnを使っても同じような値が出るのかを確認
'''

from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression().fit(scaled_housing_X_with_bias, housing_y.reshape(-1,1))

In [24]:
lin_reg.intercept_, lin_reg.coef_

(array([ 2.06855817]),
 array([[ 0.        ,  0.8296193 ,  0.11875165, -0.26552688,  0.30569623,
         -0.004503  , -0.03932627, -0.89988565, -0.870541  ]]))